<?php

declare(strict_types=1);

use App\Http\Controllers\Affiliate\AffiliateDashboardController;
use App\Http\Controllers\Api\SuggestPaletteController;
use App\Http\Controllers\Api\Tokens\ApiTokenController;
use App\Http\Controllers\Billing\BillingDashboardController;
use App\Http\Controllers\Billing\BillingSuccessController;
use App\Http\Controllers\Billing\CustomerPortalController;
use App\Http\Controllers\Billing\PricingController;
use App\Http\Controllers\Billing\StripeWebhookController;
use App\Http\Controllers\Billing\SubscribeController;
use App\Http\Controllers\BioLink\BioLinkClickController;
use App\Http\Controllers\BioLink\BioLinkController;
use App\Http\Controllers\BioLink\BioLinkItemController;
use App\Http\Controllers\BioLink\BioLinkPublicController;
use App\Http\Controllers\BotChallengeController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\CustomDomainController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OnboardingController;
use App\Http\Controllers\Profile\PasskeysController;
use App\Http\Controllers\Profile\ProfileController;
use App\Http\Controllers\Profile\SecurityController;
use App\Http\Controllers\Profile\SessionsController;
use App\Http\Controllers\PublicRedirectController;
use App\Http\Controllers\PushSubscriptionController;
use App\Http\Controllers\QrCode\AbTestController;
use App\Http\Controllers\QrCode\Ai\DetectScanAnomaliesController;
use App\Http\Controllers\QrCode\Ai\GenerateInsightsController;
use App\Http\Controllers\QrCode\Ai\SemanticSearchController;
use App\Http\Controllers\QrCode\Ai\SuggestBioLinkController;
use App\Http\Controllers\QrCode\Ai\SuggestCtaController;
use App\Http\Controllers\QrCode\Ai\SuggestQrNameController;
use App\Http\Controllers\QrCode\QrCodeAnalyticsController;
use App\Http\Controllers\QrCode\QrCodeAnalyticsPdfController;
use App\Http\Controllers\QrCode\QrCodeCompareController;
use App\Http\Controllers\QrCode\QrCodeController;
use App\Http\Controllers\QrCode\QrCodeImportController;
use App\Http\Controllers\QrCode\QrCodeZipExportController;
use App\Http\Controllers\QrCode\RedirectRuleController;
use App\Http\Controllers\QrPasswordController;
use App\Http\Controllers\QrUserTemplateController;
use App\Http\Controllers\Tag\TagController;
use App\Http\Controllers\Team\TeamBillingController;
use App\Http\Controllers\Team\TeamBrandingController;
use App\Http\Controllers\Team\TeamController;
use App\Http\Controllers\Team\TeamInvitationController;
use App\Http\Controllers\Team\TeamMemberController;
use App\Http\Controllers\Team\TeamSwitchController;
use App\Http\Controllers\WebAuthn\WebAuthnLoginController;
use App\Http\Controllers\WebAuthn\WebAuthnRegisterController;
use App\Http\Controllers\Webhook\WebhookController;
use App\Http\Middleware\CheckBotSuspicion;
use Illuminate\Foundation\Http\Middleware\PreventRequestForgery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use Symfony\Component\Yaml\Yaml;

Route::get('/', function () {
    return redirect()->route('login');
});

// Pricing — public, optional auth (shows current plan if logged in)
Route::get('/pricing', PricingController::class)->name('pricing')->middleware('web');

// OpenAPI JSON spec (generated by Scribe, converted from YAML)
Route::get('/api/openapi.json', function () {
    $yamlPath = storage_path('app/private/scribe/openapi.yaml');

    if (! file_exists($yamlPath)) {
        abort(404, 'OpenAPI spec not generated yet. Run: php artisan scribe:generate');
    }

    $yaml = (string) file_get_contents($yamlPath);
    $data = Yaml::parse($yaml);

    return response()->json($data)
        ->header('Access-Control-Allow-Origin', '*')
        ->header('Cache-Control', 'public, max-age=3600');
})->name('api.openapi.json')->middleware('throttle:60,1');

// Stripe Webhooks — public, CSRF excluded (verified by Stripe signature)
Route::post('/stripe/webhook', [StripeWebhookController::class, 'handleWebhook'])
    ->name('cashier.webhook')
    ->withoutMiddleware([PreventRequestForgery::class]);

// Branded short link redirect — custom slug chosen by user
Route::get('/s/{slug}', PublicRedirectController::class)
    ->middleware(['throttle:public-redirect', CheckBotSuspicion::class])
    ->name('qr.slug-redirect');

// Public QR redirect — rate limited, bot-suspicion checked
Route::get('/q/{hash}', PublicRedirectController::class)
    ->middleware(['throttle:public-redirect', CheckBotSuspicion::class])
    ->name('qr.redirect');

// Password-protected QR unlock
Route::get('/q/{hash}/unlock', [QrPasswordController::class, 'show'])
    ->middleware('throttle:public-redirect')
    ->name('qr.password.show');
Route::post('/q/{hash}/unlock', [QrPasswordController::class, 'verify'])
    ->middleware('throttle:qr-password')
    ->name('qr.password.verify');

// Anti-bot Turnstile challenge
Route::get('/q/{hash}/challenge', [BotChallengeController::class, 'show'])
    ->middleware('throttle:public-redirect')
    ->name('qr.challenge.show');
Route::post('/q/{hash}/challenge', [BotChallengeController::class, 'verify'])
    ->middleware('throttle:qr-password')
    ->name('qr.challenge.verify');

// Public Bio-Link pages — no auth, rate limited
Route::get('/b/{slug}', BioLinkPublicController::class)
    ->middleware('throttle:public-redirect')
    ->name('bio-link.show');

Route::get('/b/{slug}/link/{item}', BioLinkClickController::class)
    ->middleware('throttle:public-redirect')
    ->name('bio-link.click');

// Team invitation accept page — public (user may not be logged in yet)
Route::get('/invitations/{token}', [TeamInvitationController::class, 'show'])
    ->name('invitations.show')
    ->middleware('throttle:60,1');

Route::post('/locale', function (Request $request) {
    $locale = in_array($request->input('locale'), ['pl', 'en', 'de', 'es', 'fr', 'it']) ? $request->input('locale') : 'pl';
    session(['locale' => $locale]);

    return back();
})->name('locale.set');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/onboarding', [OnboardingController::class, 'show'])->name('onboarding');
    Route::post('/onboarding/complete', [OnboardingController::class, 'complete'])->name('onboarding.complete');

    Route::get('/dashboard', function () {
        return Inertia::render('Dashboard');
    })->name('dashboard');

    Route::prefix('qr')->name('qr.')->group(function () {
        Route::get('/', [QrCodeController::class, 'index'])->name('index');
        Route::get('/compare', QrCodeCompareController::class)->name('compare');
        Route::get('/create', [QrCodeController::class, 'create'])->name('create');
        Route::post('/', [QrCodeController::class, 'store'])->name('store');
        Route::post('/export', [QrCodeController::class, 'export'])->name('export');
        Route::get('/export/zip', QrCodeZipExportController::class)->name('export.zip');
        Route::post('/{qrCode}/logo', [QrCodeController::class, 'uploadLogo'])->name('logo.upload');
        Route::delete('/{qrCode}/logo', [QrCodeController::class, 'deleteLogo'])->name('logo.delete');
        Route::post('/{qrCode}/pdf', [QrCodeController::class, 'uploadPdf'])->name('pdf.upload');
        Route::get('/{qrCode}/ab-test', [AbTestController::class, 'index'])->name('ab-test.index')->middleware('plan.feature:ab-test');
        Route::patch('/{qrCode}/ab-test', [AbTestController::class, 'updateSettings'])->name('ab-test.update')->middleware('plan.feature:ab-test');
        Route::post('/{qrCode}/ab-test/variants', [AbTestController::class, 'storeVariant'])->name('ab-test.variants.store')->middleware('plan.feature:ab-test');
        Route::patch('/{qrCode}/ab-test/variants/{variant}', [AbTestController::class, 'updateVariant'])->name('ab-test.variants.update')->middleware('plan.feature:ab-test');
        Route::delete('/{qrCode}/ab-test/variants/{variant}', [AbTestController::class, 'destroyVariant'])->name('ab-test.variants.destroy')->middleware('plan.feature:ab-test');
        Route::post('/{qrCode}/ab-test/winner', [AbTestController::class, 'selectWinner'])->name('ab-test.winner')->middleware('plan.feature:ab-test');
        Route::get('/{qrCode}/rules', [RedirectRuleController::class, 'index'])->name('rules.index')->middleware('plan.feature:smart-redirect');
        Route::post('/{qrCode}/rules', [RedirectRuleController::class, 'store'])->name('rules.store')->middleware('plan.feature:smart-redirect');
        Route::post('/{qrCode}/rules/reorder', [RedirectRuleController::class, 'reorder'])->name('rules.reorder')->middleware('plan.feature:smart-redirect');
        Route::patch('/{qrCode}/rules/{rule}', [RedirectRuleController::class, 'update'])->name('rules.update')->middleware('plan.feature:smart-redirect');
        Route::delete('/{qrCode}/rules/{rule}', [RedirectRuleController::class, 'destroy'])->name('rules.destroy')->middleware('plan.feature:smart-redirect');
        // CSV Import — must come before /{qrCode} wildcard
        Route::get('/import', [QrCodeImportController::class, 'show'])->name('import')->middleware('plan.feature:bulk-import');
        Route::post('/import/upload', [QrCodeImportController::class, 'upload'])->name('import.upload')->middleware('plan.feature:bulk-import');
        Route::post('/import/process', [QrCodeImportController::class, 'process'])->name('import.process')->middleware('plan.feature:bulk-import');
        Route::get('/import/{batchId}/status', [QrCodeImportController::class, 'status'])->name('import.status')->middleware('plan.feature:bulk-import');
        // Bulk actions — must come before /{qrCode} wildcard
        Route::post('/bulk/delete', [QrCodeController::class, 'bulkDestroy'])->name('bulk.destroy');
        Route::post('/bulk/pause', [QrCodeController::class, 'bulkPause'])->name('bulk.pause');
        Route::post('/bulk/activate', [QrCodeController::class, 'bulkActivate'])->name('bulk.activate');
        Route::post('/bulk/tag', [QrCodeController::class, 'bulkTag'])->name('bulk.tag');
        Route::get('/{qrCode}/analytics', QrCodeAnalyticsController::class)->name('analytics')->middleware('plan.feature:analytics');
        Route::get('/{qrCode}/analytics/export-pdf', QrCodeAnalyticsPdfController::class)->name('analytics.export-pdf')->middleware('plan.feature:analytics');
        Route::get('/{qrCode}/edit', [QrCodeController::class, 'edit'])->name('edit');
        Route::patch('/{qrCode}', [QrCodeController::class, 'update'])->name('update');
        Route::delete('/{qrCode}', [QrCodeController::class, 'destroy'])->name('destroy');
        Route::patch('/{qrCode}/toggle-active', [QrCodeController::class, 'toggleActive'])->name('toggleActive');
        Route::post('/{qrCode}/duplicate', [QrCodeController::class, 'duplicate'])->name('duplicate');
    });

    Route::post('/api/ai/suggest-palette', SuggestPaletteController::class)->name('ai.suggest-palette')->middleware('ai.rate-limit');
    Route::post('/qr/{qrCode}/ai/suggest-name', SuggestQrNameController::class)->name('qr.ai.suggest-name')->middleware('ai.rate-limit');
    Route::post('/api/ai/suggest-cta', SuggestCtaController::class)->name('ai.suggest-cta')->middleware('ai.rate-limit');
    Route::post('/api/ai/suggest-bio-link', SuggestBioLinkController::class)->name('ai.suggest-bio-link')->middleware('ai.rate-limit');
    Route::post('/qr/{qrCode}/ai/insights', GenerateInsightsController::class)->name('qr.ai.insights')->middleware('ai.rate-limit');
    Route::post('/qr/{qrCode}/ai/detect-anomalies', DetectScanAnomaliesController::class)->name('qr.ai.detect-anomalies')->middleware('ai.rate-limit');
    Route::post('/qr/search/ai', SemanticSearchController::class)->name('qr.search.ai')->middleware('ai.rate-limit');

    // Bio-Link editor (auth required)
    Route::prefix('bio-links')->name('bio-link.')->group(function () {
        Route::get('/{bioLink}/edit', [BioLinkController::class, 'edit'])->name('edit');
        Route::patch('/{bioLink}', [BioLinkController::class, 'update'])->name('update');
        Route::post('/{bioLink}/avatar', [BioLinkController::class, 'uploadAvatar'])->name('avatar.upload');
        Route::delete('/{bioLink}/avatar', [BioLinkController::class, 'deleteAvatar'])->name('avatar.delete');
        Route::post('/{bioLink}/items', [BioLinkItemController::class, 'store'])->name('items.store');
        Route::post('/{bioLink}/items/reorder', [BioLinkItemController::class, 'reorder'])->name('items.reorder');
        Route::patch('/{bioLink}/items/{item}', [BioLinkItemController::class, 'update'])->name('items.update');
        Route::delete('/{bioLink}/items/{item}', [BioLinkItemController::class, 'destroy'])->name('items.destroy');
    });

    Route::prefix('qr-templates')->name('qr-templates.')->group(function () {
        Route::post('/', [QrUserTemplateController::class, 'store'])->name('store');
        Route::delete('/{qrUserTemplate}', [QrUserTemplateController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('tags')->name('tags.')->group(function () {
        Route::post('/', [TagController::class, 'store'])->name('store');
        Route::delete('/{tag}', [TagController::class, 'destroy'])->name('destroy');
    });

    // Webhooks outbound
    Route::prefix('webhooks')->name('webhooks.')->middleware('plan.feature:webhooks')->group(function () {
        Route::get('/', [WebhookController::class, 'index'])->name('index');
        Route::post('/', [WebhookController::class, 'store'])->name('store');
        Route::delete('/{webhook}', [WebhookController::class, 'destroy'])->name('destroy');
        Route::get('/{webhook}/deliveries', [WebhookController::class, 'deliveries'])->name('deliveries');
    });

    // Affiliate dashboard
    Route::get('/affiliate', AffiliateDashboardController::class)->name('affiliate.dashboard');

    // API token management
    Route::get('/api-tokens', [ApiTokenController::class, 'index'])->name('api-tokens.index');
    Route::post('/api-tokens', [ApiTokenController::class, 'store'])->name('api-tokens.store');
    Route::delete('/api-tokens/{tokenId}', [ApiTokenController::class, 'destroy'])->name('api-tokens.destroy');

    // Billing — Stripe Checkout + Customer Portal + Dashboard (8.10)
    Route::prefix('billing')->name('billing.')->group(function () {
        Route::get('/subscribe/{plan}', SubscribeController::class)->name('subscribe');
        Route::get('/success', BillingSuccessController::class)->name('success');
        Route::get('/portal', CustomerPortalController::class)->name('portal');
        Route::get('/dashboard', BillingDashboardController::class)->name('dashboard');
    });

    Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
    Route::get('/profile/export-data', [ProfileController::class, 'exportData'])->name('profile.export');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::get('/profile/security', SecurityController::class)->name('profile.security');
    Route::get('/profile/passkeys', PasskeysController::class)->name('profile.passkeys');

    Route::get('/profile/sessions', [SessionsController::class, 'index'])->name('profile.sessions');
    Route::delete('/profile/sessions/others', [SessionsController::class, 'destroyOthers'])->name('profile.sessions.destroyOthers');
    Route::delete('/profile/sessions/{userSession}', [SessionsController::class, 'destroy'])->name('profile.sessions.destroy');

    // Custom domains
    Route::prefix('domains')->name('domains.')->middleware('plan.feature:custom-domains')->group(function () {
        Route::get('/', [CustomDomainController::class, 'index'])->name('index');
        Route::post('/', [CustomDomainController::class, 'store'])->name('store');
        Route::post('/{customDomain}/verify', [CustomDomainController::class, 'verify'])->name('verify');
        Route::delete('/{customDomain}', [CustomDomainController::class, 'destroy'])->name('destroy');
    });

    // Web Push subscriptions
    Route::prefix('push')->name('push.')->group(function () {
        Route::get('/vapid-key', [PushSubscriptionController::class, 'vapidPublicKey'])->name('vapid-key');
        Route::post('/subscribe', [PushSubscriptionController::class, 'store'])->name('subscribe');
        Route::post('/unsubscribe', [PushSubscriptionController::class, 'destroy'])->name('unsubscribe');
    });

    // AI Chatbot
    Route::post('/chat', [ChatController::class, 'stream'])
        ->name('chat.stream')
        ->middleware('ai.rate-limit');

    // Notifications
    Route::prefix('notifications')->name('notifications.')->group(function () {
        Route::get('/', [NotificationController::class, 'index'])->name('index');
        Route::patch('/{id}/read', [NotificationController::class, 'markAsRead'])->name('read');
        Route::patch('/read-all', [NotificationController::class, 'markAllAsRead'])->name('read-all');
        Route::delete('/{id}', [NotificationController::class, 'destroy'])->name('destroy');
    });

    // Workspaces / Teams
    Route::prefix('workspaces')->name('workspaces.')->group(function () {
        Route::get('/', [TeamController::class, 'index'])->name('index');
        Route::get('/create', [TeamController::class, 'create'])->name('create');
        Route::post('/', [TeamController::class, 'store'])->name('store');
        Route::get('/{team}', [TeamController::class, 'show'])->name('show');
        Route::patch('/{team}', [TeamController::class, 'update'])->name('update');
        Route::delete('/{team}', [TeamController::class, 'destroy'])->name('destroy');
        // Member management (12.2)
        Route::patch('/{team}/members/{user}/role', [TeamMemberController::class, 'updateRole'])->name('members.role');
        Route::delete('/{team}/members/{user}', [TeamMemberController::class, 'destroy'])->name('members.destroy');
        Route::delete('/{team}/leave', [TeamMemberController::class, 'leave'])->name('members.leave');
        // Invitations (12.3)
        Route::post('/{team}/invitations', [TeamInvitationController::class, 'store'])->name('invitations.store');
        Route::delete('/{team}/invitations/{invitation}', [TeamInvitationController::class, 'destroy'])->name('invitations.destroy');
        Route::post('/invitations/{token}/accept', [TeamInvitationController::class, 'accept'])->name('invitations.accept');
        // Branding / White-label (12.5)
        Route::get('/{team}/branding', [TeamBrandingController::class, 'show'])->name('branding.show');
        Route::post('/{team}/branding', [TeamBrandingController::class, 'update'])->name('branding.update');
        // Billing (12.4)
        Route::get('/{team}/billing', [TeamBillingController::class, 'show'])->name('billing.show');
        Route::get('/{team}/billing/subscribe/{plan}', [TeamBillingController::class, 'subscribe'])->name('billing.subscribe');
        Route::get('/{team}/billing/portal', [TeamBillingController::class, 'portal'])->name('billing.portal');
    });

    // Switch workspace context (null = personal)
    Route::post('/workspace/switch/{team?}', TeamSwitchController::class)->name('workspace.switch');

    // WebAuthn passkey registration (wymaga auth)
    Route::prefix('webauthn')->name('webauthn.')->middleware('throttle:webauthn-register')->group(function () {
        Route::post('register/options', [WebAuthnRegisterController::class, 'options'])->name('register.options');
        Route::post('register', [WebAuthnRegisterController::class, 'register'])->name('register');
    });
});

// WebAuthn login (bez auth — publiczny endpoint, rate limited)
Route::prefix('webauthn')->name('webauthn.')->middleware('throttle:webauthn-login')->group(function () {
    Route::post('login/options', [WebAuthnLoginController::class, 'options'])->name('login.options');
    Route::post('login', [WebAuthnLoginController::class, 'login'])->name('login');
});
