// Lottie animation: slowly rotating gear — personalize step
export default {
    v: '5.9.0',
    fr: 30,
    ip: 0,
    op: 120,
    w: 200,
    h: 200,
    nm: 'Personalize',
    ddd: 0,
    assets: [],
    layers: [
        {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'Gear',
            sr: 1,
            ks: {
                o: { a: 0, k: 100 },
                s: { a: 0, k: [100, 100] },
                p: { a: 0, k: [100, 100, 0] },
                a: { a: 0, k: [0, 0, 0] },
                r: { a: 1, k: [{ t: 0, s: [0] }, { t: 120, s: [360] }] },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'el',
                    d: 1,
                    s: { a: 0, k: [80, 80] },
                    p: { a: 0, k: [0, 0] },
                    nm: 'Inner',
                },
                {
                    ty: 'st',
                    c: { a: 0, k: [0.486, 0.227, 0.929, 1] },
                    o: { a: 0, k: 100 },
                    w: { a: 0, k: 14 },
                    lc: 2,
                    lj: 2,
                    d: [{ n: 'dash', nm: 'Dash', v: { a: 0, k: 24 } }, { n: 'gap', nm: 'Gap', v: { a: 0, k: 10 } }],
                    nm: 'Dashed stroke',
                },
                {
                    ty: 'el',
                    d: 1,
                    s: { a: 0, k: [40, 40] },
                    p: { a: 0, k: [0, 0] },
                    nm: 'Center',
                },
                {
                    ty: 'fl',
                    c: { a: 0, k: [0.486, 0.227, 0.929, 1] },
                    o: { a: 0, k: 100 },
                    r: 1,
                    nm: 'Fill',
                },
            ],
            ip: 0,
            op: 120,
            st: 0,
        },
    ],
}
