// Lottie animation: checkmark draw-on — ready step
export default {
    v: '5.9.0',
    fr: 30,
    ip: 0,
    op: 60,
    w: 200,
    h: 200,
    nm: 'Ready',
    ddd: 0,
    assets: [],
    layers: [
        {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'Circle bg',
            sr: 1,
            ks: {
                o: { a: 1, k: [{ t: 0, s: [0] }, { t: 15, s: [100] }] },
                s: { a: 1, k: [{ t: 0, s: [60, 60] }, { t: 20, s: [105, 105] }, { t: 30, s: [100, 100] }] },
                p: { a: 0, k: [100, 100, 0] },
                a: { a: 0, k: [0, 0, 0] },
                r: { a: 0, k: 0 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'el',
                    d: 1,
                    s: { a: 0, k: [140, 140] },
                    p: { a: 0, k: [0, 0] },
                    nm: 'Ellipse',
                },
                {
                    ty: 'fl',
                    c: { a: 0, k: [0.486, 0.227, 0.929, 1] },
                    o: { a: 0, k: 100 },
                    r: 1,
                    nm: 'Fill',
                },
            ],
            ip: 0,
            op: 60,
            st: 0,
        },
        {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'Checkmark',
            sr: 1,
            ks: {
                o: { a: 1, k: [{ t: 15, s: [0] }, { t: 30, s: [100] }] },
                s: { a: 0, k: [100, 100] },
                p: { a: 0, k: [100, 100, 0] },
                a: { a: 0, k: [0, 0, 0] },
                r: { a: 0, k: 0 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'sh',
                    d: 1,
                    ks: {
                        a: 0,
                        k: {
                            i: [[0, 0], [0, 0], [0, 0]],
                            o: [[0, 0], [0, 0], [0, 0]],
                            v: [[-28, 0], [-8, 22], [32, -20]],
                            c: false,
                        },
                    },
                    nm: 'Check path',
                },
                {
                    ty: 'st',
                    c: { a: 0, k: [1, 1, 1, 1] },
                    o: { a: 0, k: 100 },
                    w: { a: 0, k: 10 },
                    lc: 2,
                    lj: 2,
                    nm: 'Stroke',
                },
                {
                    ty: 'tm',
                    s: { a: 1, k: [{ t: 20, s: [0] }, { t: 50, s: [100] }] },
                    e: { a: 0, k: 100 },
                    o: { a: 0, k: 0 },
                    m: 1,
                    nm: 'Trim',
                },
            ],
            ip: 0,
            op: 60,
            st: 0,
        },
    ],
}
