// Lottie animation: pulsing QR-Master brand circle — welcome step
export default {
    v: '5.9.0',
    fr: 30,
    ip: 0,
    op: 90,
    w: 200,
    h: 200,
    nm: 'Welcome',
    ddd: 0,
    assets: [],
    layers: [
        {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'Outer ring',
            sr: 1,
            ks: {
                o: { a: 1, k: [{ t: 0, s: [20] }, { t: 45, s: [60] }, { t: 90, s: [20] }] },
                s: { a: 1, k: [{ t: 0, s: [80, 80] }, { t: 45, s: [110, 110] }, { t: 90, s: [80, 80] }] },
                p: { a: 0, k: [100, 100, 0] },
                a: { a: 0, k: [0, 0, 0] },
                r: { a: 0, k: 0 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'el',
                    d: 1,
                    s: { a: 0, k: [160, 160] },
                    p: { a: 0, k: [0, 0] },
                    nm: 'Ellipse',
                },
                {
                    ty: 'st',
                    c: { a: 0, k: [0.486, 0.227, 0.929, 1] },
                    o: { a: 0, k: 100 },
                    w: { a: 0, k: 6 },
                    lc: 2,
                    lj: 2,
                    nm: 'Stroke',
                },
            ],
            ip: 0,
            op: 90,
            st: 0,
        },
        {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'Inner circle',
            sr: 1,
            ks: {
                o: { a: 0, k: 100 },
                s: { a: 1, k: [{ t: 0, s: [90, 90] }, { t: 45, s: [100, 100] }, { t: 90, s: [90, 90] }] },
                p: { a: 0, k: [100, 100, 0] },
                a: { a: 0, k: [0, 0, 0] },
                r: { a: 0, k: 0 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'el',
                    d: 1,
                    s: { a: 0, k: [100, 100] },
                    p: { a: 0, k: [0, 0] },
                    nm: 'Ellipse',
                },
                {
                    ty: 'fl',
                    c: { a: 0, k: [0.486, 0.227, 0.929, 1] },
                    o: { a: 0, k: 100 },
                    r: 1,
                    nm: 'Fill',
                },
            ],
            ip: 0,
            op: 90,
            st: 0,
        },
    ],
}
